### PR TITLE
fix(CORS): add cors to async'ly registered views

### PR DESCRIPTION
**Pull request by akloeckner**
1. store `cors_origins` in `HomeAssistantHTTP`'s `self.app` to make it persistent
2. this `self.app` is passed to `HomeAssistantView`'s `register()` already
3. set `HomeAssistantView`'s `self.cors_allowed`  to `True`, if `cors_origins` is truthy in `app`
4. this will enable `allow_cors` as per [1]

if `allow_cors` is called multiple times per resource, this should not harm, because it is checked in [2].

I have not tested this change, so it's just a thought for the time being.

[1]
https://github.com/akloeckner/home-assistant/blob/265295ff4a31d8da0516e55fdfe65e1c287ddfa8/homeassistant/components/http/view.py#L106

[2]
https://github.com/akloeckner/home-assistant/blob/edf70e9f06639123ff4221f1ab56b775e3303cd8/homeassistant/components/http/cors.py#L55

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast homeassistant tests`)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

If the code communicates with devices, web services, or third-party tools:

- [ ] The [manifest file][manifest-docs] has all fields filled out correctly.  
      Updated and included derived files by running: `python3 -m script.hassfest`.
- [ ] New or updated dependencies have been added to `requirements_all.txt`.  
      Updated by running `python3 -m script.gen_requirements_all`.
- [ ] Untested files have been added to `.coveragerc`.

The integration reached or maintains the following [Integration Quality Scale][quality-scale]:

- [ ] No score or internal
- [ ] 🥈 Silver
- [ ] 🥇 Gold
- [ ] 🏆 Platinum

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/core/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+-label%3Awaiting-for-upstream+sort%3Acreated-desc+review%3Anone

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
[quality-scale]: https://developers.home-assistant.io/docs/en/next/integration_quality_scale_index.html
[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by rchl** [comment]
I've tested this change and it works but I don't know the code well enough to say whether it's a good solution.

Potentially there could be cases where implementations of `HomeAssistantView` should never get CORS enabled in which case this change will be bad.

I honestly don't understand what was wrong with my original fix and why the same logic isn't a problem for other REST resources. And since I don't know what was exactly wrong with my solution, I also don't understand what they expect.

**Comment by rchl** [comment]
Re-reading my original PR, maybe the issue that should actually be fixed is this:

> If cors is not initialized correctly for later registered views, that's a bug.

This is a response to my description of the issue:

> CORS has worked for other APIs but not this one because other API
endpoints are registered using register_view() in the "api" component [1]
and all of those are automatically CORS-enabled when app is ready [2].
>
> The history component, on the other hand, also registers the
"HistoryPeriodView" using register_view() but does it later, after the
app is ready and that means it doesn't get the same treatment.

**Comment by akloeckner** [comment]
I guess, they *have* the option to explicitly set CORS, or not. So, I think it's logical to want to apply the option to all endpoints. Plus, their policy as to “work around and fix properly later“ is just different than ours. :-)

You're saying, the same logic (hardcode CORS to true) is applied elsewhere, though? That's weird, I agree. On the other hand, what else would the option in `HomeAssistantView` be good for...

Thanks for testing. Good to know, it works. The review will have to show, if it's a good fix. I'll have to find out what's wrong with the failing tests though, I fear. :-/ And I have no clue to be honest...

**Comment by rchl** [comment]
> I guess, they _have_ the option to explicitly set CORS, or not. So, I think it's logical to want to apply the option to all endpoints.

Some views might be designed to be local-only, I would think. But I haven't checked what kind of views are there exactly.

**Pull request closed without merging**
